---
output:
  word_document: default
  pdf_document: default
  html_document: default
---
TASK 3 Bagging and Random Forests 20 points
```{r}
library(randomForest)
library(MASS)
require(tree)
require(devtools)
require(ISLR)
require(MASS)  
require(randomForest)
require(gbm) 
library(caret)


```

```{r}
set.seed(1)
bag.boston = randomForest( medv~., data = Boston , subset = train, mtry =13, importance =TRUE )
bag.boston
```

```{r}
yhat.bag = predict (bag.boston , newdata = Boston [-train ,])
plot(yhat.bag , boston.test)
abline (0 ,1)
mean ((yhat.bag - boston.test)^2)

```

```{r}
bag.boston = randomForest( medv~., data= Boston , subset =train ,mtry =13, ntree =25)
yhat.bag = predict (bag.boston , newdata = Boston [-train ,])
mean (( yhat.bag - boston.test)^2)
```

```{r}
set.seed (1)
rf.boston = randomForest(medv~., data=Boston , subset =train ,mtry =6, importance =TRUE)
yhat.rf = predict (rf.boston , newdata = Boston [-train ,])
mean ((yhat.rf - boston.test)^2)
```

```{r}
importance (rf.boston )
```

```{r}
varImpPlot (rf.boston )
```

