---
output:
  word_document: default
  html_document: default
---
TASK1 -- The execution of task 1 is below.
Here are the required packages.

```{r include=FALSE}
require(tree)
require(devtools)
require(ISLR)
require(MASS)  
require(randomForest)
library(gbm)  
```
Using classification trees to analyze the Carseats data set.Sales is a continuous variable, and so we begin by recoding it as a binary variable.
```{r include=FALSE}
library (ISLR )
attach ( Carseats )
High= ifelse (Sales <=8 ," No"," Yes ")
Carseats = data.frame (Carseats , High)
tree.carseats =tree (High~.-Sales , Carseats )
```

```{r }
summary (tree.carseats )

```

```{r}
plot(tree.carseats )
text(tree.carseats ,pretty =0)
```

```{r}
tree.carseats
```


```{r}
set.seed (2)
train = sample (1: nrow( Carseats ), 200)
Carseats.test= Carseats [-train ,]
High.test=High[-train ]
tree.carseats =tree (High~.-Sales , Carseats , subset =train )
tree.pred = predict ( tree.carseats , Carseats.test ,type ="class")
table ( tree.pred ,High.test)
```

```{r}
set.seed (3)
cv.carseats =cv.tree(tree.carseats ,FUN = prune.misclass )
names (cv.carseats )
```

```{r}
cv.carseats
```

```{r}
par ( mfrow =c(1 ,2) )
plot(cv.carseats$size ,cv.carseats$dev , type ="b")
plot(cv.carseats$k ,cv.carseats$dev , type ="b")
```

```{r}
prune.carseats = prune.misclass ( tree.carseats , best =9)
plot( prune.carseats )
text( prune.carseats , pretty =0)
```

```{r}
tree.pred = predict ( prune.carseats , Carseats.test , type ="class")
table ( tree.pred ,High.test)
```

```{r}
prune.carseats = prune.misclass ( tree.carseats , best =15)
plot( prune.carseats )
text( prune.carseats , pretty =0)
tree.pred = predict ( prune.carseats , Carseats.test , type ="class")
table ( tree.pred ,High.test)
```




